In [3]:
import numpy as np

In [25]:
a = np.array([1, 2, 3, 4])
x = np.array([3, 5, 6])
X = np.ones((len(x), len(a)))
X[:,1] = x
X[:,2] = x**2
X[:,3] = x**3
print(X)
y = np.einsum('i,ji->j',a, X)
for i in range(X.shape[0]):
    print(np.dot(X[i], a))
y = y.reshape(-1, 1)
print(y.shape)


[[  1.   3.   9.  27.]
 [  1.   5.  25. 125.]
 [  1.   6.  36. 216.]]
142.0
586.0
985.0
(3, 1)


In [30]:
X1 = np.array([np.ones(len(x)), x, x**2, x**3]).T
print(X1)

[[  1.   3.   9.  27.]
 [  1.   5.  25. 125.]
 [  1.   6.  36. 216.]]


In [35]:
Xl = []
for i in range(4):
    Xl.append(x**(i+1))
Xl.append(np.ones(len(x)))
X1 = np.array(Xl).astype(int).T
print(X1)

[[   3    9   27   81    1]
 [   5   25  125  625    1]
 [   6   36  216 1296    1]]


In [37]:
expected_coeffs_ex12 = np.expand_dims(np.array(\
                            [3.55626657,-4.85071512,13.58932204,-9.0132505,1.75782422]),axis=1)
print(expected_coeffs_ex12)

[[ 3.55626657]
 [-4.85071512]
 [13.58932204]
 [-9.0132505 ]
 [ 1.75782422]]


In [36]:
w = np.linalg.inv(X.T @ X) @ X.T @ targets
print(w)

NameError: name 'targets' is not defined